import os
import io
import zipfile
import json
import struct
from typing import Dict, Any, List
from shapely.geometry import shape, MultiPolygon, Polygon

# Standard WGS84 PRJ file content
WGS84_PRJ_WKT = 'GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]]'

class GISExportEngine:
    """
    Automated Multi-Format GIS Exporter.
    
    Generates:
    1. GeoJSON (RFC 7946 compliant)
    2. OGC KML with altitude modes and styled polygon styling
    3. ESRI Shapefile Bundle (.shp, .shx, .dbf, .prj) packaged into .zip
    """

    @staticmethod
    def export_geojson(risk_zones_dict: Dict[str, Any], sim_meta: Dict[str, Any]) -> str:
        """
        Generates standard GeoJSON FeatureCollection text.
        """
        features = []
        for level_key, zone in risk_zones_dict.items():
            geom = zone.get("geometry")
            if geom and geom.get("coordinates"):
                features.append({
                    "type": "Feature",
                    "properties": {
                        "risk_level": zone.get("risk_level", level_key),
                        "color": zone.get("color", "#EF4444"),
                        "area_sqkm": zone.get("area_sqkm", 0.0),
                        "max_depth_m": zone.get("max_depth_m", 0.0),
                        "max_velocity_ms": zone.get("max_velocity_ms", 0.0),
                        "min_arrival_time_min": zone.get("min_arrival_time_min", 0.0),
                        "simulation_id": sim_meta.get("simulation_id", "")
                    },
                    "geometry": geom
                })

        geojson_obj = {
            "type": "FeatureCollection",
            "name": f"DamFlood_RiskZones_{sim_meta.get('simulation_id', 'export')}",
            "crs": {
                "type": "name",
                "properties": {"name": "urn:ogc:def:crs:OGC:1.3:CRS84"}
            },
            "features": features
        }
        return json.dumps(geojson_obj, indent=2)

    @staticmethod
    def export_kml(risk_zones_dict: Dict[str, Any], sim_meta: Dict[str, Any]) -> str:
        """
        Generates standard OGC KML 2.2 with color tiers and placemarks.
        """
        kml_header = """<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>Dam Breach Inundation Risk Zones</name>
    <description>Hydrodynamic flood risk zones generated by SIH Dam Inundation Platform</description>
    
    <!-- Style definitions (AABBGGRR) -->
    <Style id="level3_critical">
      <LineStyle><color>ff0000ff</color><width>2</width></LineStyle>
      <PolyStyle><color>7f0000ff</color></PolyStyle>
    </Style>
    <Style id="level2_high">
      <LineStyle><color>ff0080ff</color><width>2</width></LineStyle>
      <PolyStyle><color>7f0080ff</color></PolyStyle>
    </Style>
    <Style id="level1_warning">
      <LineStyle><color>ff00ffff</color><width>2</width></LineStyle>
      <PolyStyle><color>7f00ffff</color></PolyStyle>
    </Style>
"""
        kml_body = []
        for level_key, zone in risk_zones_dict.items():
            geom = zone.get("geometry")
            if not geom or not geom.get("coordinates"):
                continue

            style_id = "level3_critical" if "3" in level_key else ("level2_high" if "2" in level_key else "level1_warning")
            risk_name = zone.get("risk_level", level_key)
            area = zone.get("area_sqkm", 0.0)
            depth = zone.get("max_depth_m", 0.0)
            vel = zone.get("max_velocity_ms", 0.0)

            # Support Polygon and MultiPolygon
            coords_lists = []
            if geom.get("type") == "Polygon":
                coords_lists = [geom["coordinates"][0]] # outer ring
            elif geom.get("type") == "MultiPolygon":
                coords_lists = [poly[0] for poly in geom["coordinates"]]

            for idx, ring in enumerate(coords_lists):
                coord_str = " ".join([f"{pt[0]},{pt[1]},0" for pt in ring])
                kml_body.append(f"""    <Placemark>
      <name>{risk_name} (Part {idx+1})</name>
      <description>Flooded Area: {area} km2 | Max Depth: {depth} m | Max Velocity: {vel} m/s</description>
      <styleUrl>#{style_id}</styleUrl>
      <Polygon>
        <extrude>1</extrude>
        <altitudeMode>clampToGround</altitudeMode>
        <outerBoundaryIs>
          <LinearRing>
            <coordinates>{coord_str}</coordinates>
          </LinearRing>
        </outerBoundaryIs>
      </Polygon>
    </Placemark>""")

        kml_footer = """  </Document>
</kml>"""
        return kml_header + "\n".join(kml_body) + "\n" + kml_footer

    @classmethod
    def export_shapefile_zip(cls, risk_zones_dict: Dict[str, Any], sim_meta: Dict[str, Any], output_zip_path: str) -> str:
        """
        Creates ESRI Shapefile component files (.shp, .shx, .dbf, .prj) and packages into a .zip.
        Uses pure Python binary packager so no external native drivers are required.
        """
        base_name = f"flood_risk_zones_{sim_meta.get('simulation_id', 'sim')[:8]}"
        
        # We write standard binary shapefile polygons
        # Prepare records
        records = []
        for level_key, zone in risk_zones_dict.items():
            geom = zone.get("geometry")
            if geom and geom.get("coordinates"):
                poly_geom = shape(geom)
                if not poly_geom.is_empty:
                    records.append({
                        "risk_level": zone.get("risk_level", level_key)[:15],
                        "area_sqkm": float(zone.get("area_sqkm", 0.0)),
                        "max_depth": float(zone.get("max_depth_m", 0.0)),
                        "max_vel": float(zone.get("max_velocity_ms", 0.0)),
                        "geometry": poly_geom
                    })

        # Generate files in memory or temp
        zip_buffer = io.BytesIO()
        with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zip_file:
            # 1. PRJ projection file
            zip_file.writestr(f"{base_name}.prj", WGS84_PRJ_WKT)

            # 2. GeoJSON companion file
            geojson_str = cls.export_geojson(risk_zones_dict, sim_meta)
            zip_file.writestr(f"{base_name}.geojson", geojson_str)

            # 3. KML companion file
            kml_str = cls.export_kml(risk_zones_dict, sim_meta)
            zip_file.writestr(f"{base_name}.kml", kml_str)

            # 4. Standard Shapefile binary structure (.shp, .shx, .dbf)
            shp_bytes, shx_bytes, dbf_bytes = cls._build_shapefile_binary(records)
            zip_file.writestr(f"{base_name}.shp", shp_bytes)
            zip_file.writestr(f"{base_name}.shx", shx_bytes)
            zip_file.writestr(f"{base_name}.dbf", dbf_bytes)

            # 5. Metadata text file
            meta_txt = f"""SIH 2026 Dam Break Inundation Flood Analysis Export
Simulation ID: {sim_meta.get('simulation_id', 'N/A')}
Coordinate Reference System: EPSG:4326 (WGS 84)
Files included:
- {base_name}.shp (Polygon Shapefile Geometry)
- {base_name}.shx (Spatial Index)
- {base_name}.dbf (Attribute Table)
- {base_name}.prj (Projection WKT)
- {base_name}.geojson (GeoJSON standard)
- {base_name}.kml (Google Earth KML)
"""
            zip_file.writestr("README_METADATA.txt", meta_txt)

        # Write to output_zip_path
        os.makedirs(os.path.dirname(os.path.abspath(output_zip_path)), exist_ok=True)
        with open(output_zip_path, "wb") as f:
            f.write(zip_buffer.getvalue())

        return output_zip_path

    @staticmethod
    def _build_shapefile_binary(records: List[Dict[str, Any]]) -> (bytes, bytes, bytes):
        """
        Builds standard compliant binary ESRI Shapefile Polygon (ShapeType 5).
        """
        # SHP & SHX Headers
        # Calculate bounding box
        all_geoms = [r["geometry"] for r in records if not r["geometry"].is_empty]
        if all_geoms:
            from shapely.ops import unary_union
            u = unary_union(all_geoms)
            min_x, min_y, max_x, max_y = u.bounds
        else:
            min_x, min_y, max_x, max_y = 0.0, 0.0, 0.0, 0.0

        shp_body = bytearray()
        shx_body = bytearray()

        file_offset_words = 50 # 100 bytes header / 2

        for rec_num, rec in enumerate(records, 1):
            geom = rec["geometry"]
            poly_parts = []
            if isinstance(geom, Polygon):
                poly_parts = [list(geom.exterior.coords)]
            elif isinstance(geom, MultiPolygon):
                for p in geom.geoms:
                    poly_parts.append(list(p.exterior.coords))

            num_parts = len(poly_parts)
            num_points = sum(len(p) for p in poly_parts)
            if num_points == 0:
                continue

            bx_min, by_min, bx_max, by_max = geom.bounds

            # Record Header: Record Number (Big Endian 4B), Content Length words (Big Endian 4B)
            rec_content_length = (44 + 4 * num_parts + 16 * num_points) // 2

            rec_header = struct.pack(">ii", rec_num, rec_content_length)
            
            # Record Content (Little Endian):
            # ShapeType = 5 (Polygon, 4B)
            # Box = 4 doubles (32B)
            # NumParts = int (4B)
            # NumPoints = int (4B)
            # Parts = int array (4 * num_parts B)
            # Points = double array (16 * num_points B)
            content = bytearray()
            content.extend(struct.pack("<i", 5)) # Polygon
            content.extend(struct.pack("<dddd", bx_min, by_min, bx_max, by_max))
            content.extend(struct.pack("<ii", num_parts, num_points))

            part_offset = 0
            for p in poly_parts:
                content.extend(struct.pack("<i", part_offset))
                part_offset += len(p)

            for p in poly_parts:
                for pt in p:
                    content.extend(struct.pack("<dd", float(pt[0]), float(pt[1])))

            # Append to SHP
            shp_body.extend(rec_header)
            shp_body.extend(content)

            # Append to SHX (Offset words Big Endian 4B, Content Length words Big Endian 4B)
            shx_body.extend(struct.pack(">ii", file_offset_words, rec_content_length))
            file_offset_words += 4 + rec_content_length

        total_shp_words = (100 + len(shp_body)) // 2
        total_shx_words = (100 + len(shx_body)) // 2

        # 100-byte Main Headers
        def make_header(file_len_words):
            hdr = bytearray(100)
            # File Code (9994 Big Endian)
            struct.pack_into(">i", hdr, 0, 9994)
            # File Length in 16-bit words (Big Endian)
            struct.pack_into(">i", hdr, 24, file_len_words)
            # Version (1000 Little Endian)
            struct.pack_into("<i", hdr, 28, 1000)
            # Shape Type (5 = Polygon Little Endian)
            struct.pack_into("<i", hdr, 32, 5)
            # Bounding Box
            struct.pack_into("<dddd", hdr, 36, min_x, min_y, max_x, max_y)
            return bytes(hdr)

        shp_bytes = make_header(total_shp_words) + bytes(shp_body)
        shx_bytes = make_header(total_shx_words) + bytes(shx_body)

        # 3. DBF III File
        # Header (32 bytes) + Field Descriptors (32 bytes * 4 fields) + Term (\r 1 byte)
        fields = [
            ("RISK_LVL", "C", 16, 0),
            ("AREA_SQKM", "N", 12, 3),
            ("MAX_DP_M", "N", 10, 2),
            ("MAX_VL_MS", "N", 10, 2)
        ]
        num_records = len(records)
        header_len = 32 + len(fields) * 32 + 1
        record_len = 1 + 16 + 12 + 10 + 10 # 1 byte deletion flag + fields = 49 bytes

        dbf_hdr = bytearray(32)
        dbf_hdr[0] = 0x03 # dBASE III
        dbf_hdr[1] = 126 # Year 2026 - 1900
        dbf_hdr[2] = 9   # Month
        dbf_hdr[3] = 2   # Day
        struct.pack_into("<I", dbf_hdr, 4, num_records)
        struct.pack_into("<H", dbf_hdr, 8, header_len)
        struct.pack_into("<H", dbf_hdr, 10, record_len)

        dbf_fields = bytearray()
        for fname, ftype, flen, fdec in fields:
            fdesc = bytearray(32)
            fname_bytes = fname.encode("ascii")[:10]
            fdesc[0:len(fname_bytes)] = fname_bytes
            fdesc[11] = ord(ftype)
            fdesc[16] = flen
            fdesc[17] = fdec
            dbf_fields.extend(fdesc)

        dbf_records = bytearray()
        for r in records:
            dbf_records.append(0x20) # Not deleted
            dbf_records.extend(r["risk_level"][:16].ljust(16).encode("ascii", "ignore"))
            dbf_records.extend(f"{r['area_sqkm']:12.3f}".encode("ascii"))
            dbf_records.extend(f"{r['max_depth']:10.2f}".encode("ascii"))
            dbf_records.extend(f"{r['max_vel']:10.2f}".encode("ascii"))

        dbf_bytes = bytes(dbf_hdr) + bytes(dbf_fields) + b"\r" + bytes(dbf_records) + b"\x1A"

        return shp_bytes, shx_bytes, dbf_bytes
